routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
            Route::get('/', function () {
                return redirect('admin-login');
            });
            Route::get('/__clear__', function(){

            Artisan::call('cache:clear');
            //Artisan::call('route:clear');
            Artisan::call('config:clear');
            Artisan::call('route:cache');
            Artisan::call('config:cache');
            Artisan::call('view:clear');



return 'cache cleard';
});



Route::get('/merchant_maxboost','App\Http\Controllers\API\UserController@merchant_maxboost')->name('merchant_maxboost');
Route::get('/client_maxboost','App\Http\Controllers\API\UserController@client_maxboost')->name('client_maxboost');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::post('/add-mer', [App\Http\Controllers\HomeController::class, 'addMerchant'])->name('add_mer');

Auth::routes();

Route::get('/home', 'App\Http\Controllers\HomeController@index')->name('home')->middleware('auth');

        Route::group(['middleware' => 'auth'], function () {
    	
    		Route::get('icons', ['as' => 'pages.icons', 'uses' => 'App\Http\Controllers\PageController@icons']);
    		Route::get('maps', ['as' => 'pages.maps', 'uses' => 'App\Http\Controllers\PageController@maps']);
    		Route::get('notifications', ['as' => 'pages.notifications', 'uses' => 'App\Http\Controllers\PageController@notifications']);
    		Route::get('rtl', ['as' => 'pages.rtl', 'uses' => 'App\Http\Controllers\PageController@rtl']);
    		Route::get('tables', ['as' => 'pages.tables', 'uses' => 'App\Http\Controllers\PageController@tables']);
    		Route::get('typography', ['as' => 'pages.typography', 'uses' => 'App\Http\Controllers\PageController@typography']);
    		Route::get('upgrade', ['as' => 'pages.upgrade', 'uses' => 'App\Http\Controllers\PageController@upgrade']);
        
            
        });



Route::post('DeleteMerchantUsers','App\Http\Controllers\MerchantsDataController@DeleteMerchantUsers')->name('DeleteMerchantUsers');



//Route::post('addNewMerchantUser', 'MerchantsDataController@addNewMerchantUser');  
Route::post('addNewMerchantUser','App\Http\Controllers\MerchantsDataController@addNewMerchantUser')->name('addNewMerchantUser');


Route::post('do_verify','App\Http\Controllers\UserController@do_verify')->name('do_verify');


Route::post('do_login','App\Http\Controllers\UserController@do_login')->name('do_login');
Route::get('admin-login','App\Http\Controllers\UserController@admin_login')->name('admin_login');

Route::post('forgot-password','App\Http\Controllers\UserController@reset_password')->name('forgot-password');
Route::get('forgot-password','App\Http\Controllers\UserController@reset_link')->name('reset-password');
Route::post('update-password','App\Http\Controllers\UserController@update')->name('update-password');
Route::get('change-password','App\Http\Controllers\UserController@update_form')->name('change-password');
Route::post('merchant/changePassword','App\Http\Controllers\UserController@merchantChangePassword'); 		//By Muhammad Waqar


Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'App\Http\Controllers\UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'App\Http\Controllers\ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'App\Http\Controllers\ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'App\Http\Controllers\ProfileController@password']);
// ClientDataController





    Route::get('client-edit/{id}','App\Http\Controllers\ClientDataController@clientEdit')->name('clientEdit');
    Route::get('add-client','App\Http\Controllers\ClientDataController@addClient')->name('addClient');
    Route::post('create-client','App\Http\Controllers\ClientDataController@createClient')->name('createClient');
    Route::post('update-client/{id}','App\Http\Controllers\ClientDataController@updateClient')->name('updateClient');
    Route::get('client-delete/{id}','App\Http\Controllers\ClientDataController@clientDelete')->name('clientDelete');

// MerchantsDataController

    Route::get('add-merchant','App\Http\Controllers\MerchantsDataController@addMerchant')->name('addMerchant');
    Route::post('createMerchant','App\Http\Controllers\MerchantsDataController@createMerchant')->name('createMerchant');
    Route::get('edit-merchant/{id}','App\Http\Controllers\MerchantsDataController@editMerchant')->name('editMerchant');
    Route::post('update-merchant/{id}','App\Http\Controllers\MerchantsDataController@updateMerchant')->name('updateMerchant');
    Route::get('merchant-delete/{id}','App\Http\Controllers\MerchantsDataController@merchantDelete')->name('merchantDelete');

// FundingNodeController

    Route::get('funding-home-view','App\Http\Controllers\FundingNodeController@fundingHomeView')->name('fundingHomeView');
    Route::get('edit-funding/{id}','App\Http\Controllers\FundingNodeController@editFunding')->name('editFunding');
    Route::post('update-funding/{id}','App\Http\Controllers\FundingNodeController@updateFunding')->name('updateFunding');


// RoutingNodeController

    Route::get('routing-home-view','App\Http\Controllers\RoutingNodeController@routingHomeView')->name('routingHomeView');
    Route::get('edit-routing/{id}','App\Http\Controllers\RoutingNodeController@editRouting')->name('editRouting');
    Route::post('update-routing/{id}','App\Http\Controllers\RoutingNodeController@updateRouting')->name('updateRouting');
    
    
    // AdminInfo Route 
     Route::get('show-admin-info','App\Http\Controllers\RoutingNodeController@showAdminInfo')->name('showAdminInfo');
      Route::post('update-admin-email','App\Http\Controllers\RoutingNodeController@updateAdminEmail')->name('updateAdminEmail');
     
// TransactionController 
    Route::get('get-transactions','App\Http\Controllers\TransactionController@getTransactions')->name('getTransactions');
    Route::get('filter-transections','App\Http\Controllers\TransactionController@filterTransections')->name('filterTransections');


//  TransectionAlphaController
    Route::get('get-transactions-alpha','App\Http\Controllers\TransectionAlphaController@getTransactionsalpha')->name('getTransactionsalpha');
    Route::get('filter-transection','App\Http\Controllers\TransectionAlphaController@filterTransection')->name('filterTransection');
});

// Email Beta 
Route::get('/send-mail','App\Http\Controllers\MailController@send_mail')->name('send_mail');
Route::get('/daily_mails','App\Http\Controllers\MailController@daily_mails')->name('daily_mails');
Route::get('/weekly_mails','App\Http\Controllers\MailController@weekly_mails')->name('weekly_mails');
Route::get('/monthly_mails','App\Http\Controllers\MailController@monthly_mails')->name('monthly_mails');



// Daily Manual Email Route
Route::post('/daily-manual-email','App\Http\Controllers\MailController@dailyManualEmail')->name('dailyMail');
// Weekly Manual Email Route
Route::post('/weekly-manual-email','App\Http\Controllers\MailController@weeklyManualEmail')->name('weeklyMail');
// Monthly Manual Email Route

Route::any('/change-status','App\Http\Controllers\MailController@changeStatus');



// E-mail Alpha
Route::post('/is-email-allow','App\Http\Controllers\MailController@isEmailAllow');
Route::post('/boot-email','App\Http\Controllers\MailController@bootManualEmail');
Route::get('/merchant/requestNewMemberToken/{id}','App\Http\Controllers\MailController@merchantRequestNewMemberToken');		//By Muhammad Waqar
Route::post('/merchant/verify2faCode','App\Http\Controllers\MailController@merchantVerify2faCode');		//By Muhammad Waqar



Route::get('/daily_alpha_mails','App\Http\Controllers\MailController@daily_alpha_mails')->name('daily_alpha_mails');
Route::get('/weekly_alpha_mails','App\Http\Controllers\MailController@weekly_alpha_mails')->name('weekly_alpha_mails');
Route::get('/monthly_alpha_mails','App\Http\Controllers\MailController@monthly_mails')->name('monthly_alpha_mails');

Route::get('/password-change','App\Http\Controllers\ProfileController@password_2fa')->name('password-change');
Route::get('/password-change/2fa','App\Http\Controllers\ProfileController@verify_2fa')->name('password-change.2fa');
Route::post('/admin-password/update','App\Http\Controllers\ProfileController@admin_password_update')->name('admin-password.update');

resources/views/dashboard.blade.php
@extends('layouts.app', ['pageSlug' => 'dashboard'])

@section('content')
 @if(\Illuminate\Support\Facades\Auth::user()->type == 'beta')
 

<div class="row">
        <div class="col-lg-4">
            <div class="btn card card-chart">
                
                <div class="card-header">
                <a href="{{route('user.index')}}">
                    <h5 class="card-category text-primary">Total Merchants</h5>
                    <h3 class="card-title counter"><i class="tim-icons icon-single-02 text-primary"></i> {{$merchant}}</h3>
                </a>
                </div>
            </div>
        </div>
        <div class=" col-lg-4">
            <div class="btn card card-chart">
                <div class="card-header">
                    <a href="{{route('profile.edit')}}">
                    <h3 class="card-category text-info">Total Clients</h3>
                    <h3 class="card-title counter"><i class="tim-icons icon-single-02 text-info"></i>{{$client}}</h3>
                    </a>
                </div>
            </div>
        </div>
        <div class=" col-lg-4">
            <div class="btn card card-chart">
           
                
                <div class="card-header">
               
                    <h5 class="card-category text-success">Total Users</h5>
                    <h3 class="card-title counter"><i class="tim-icons icon-send text-success"></i>{{$merchant+$client}}</h3>
              
                </div>
                

            </div>
        </div>
        <div class=" col-lg-4">
            <div class="btn card card-chart">
           
                <a href="{{ route('getTransactions') }}">
                <div class="card-header">
                 
                    <h5 class="card-category text-warning">Total Transections</h5>
                    <h3 class="card-title counter"><i class="tim-icons icon-chart-bar-32 text-warning"></i>{{$Transection}}</h3>
                 
                </div>
                </a>

            </div>
        </div>
    </div>
@endif
 @if(\Illuminate\Support\Facades\Auth::user()->type == 'alpha')
<div class="row">
        <div class="col-lg-4">
            <div class="btn card card-chart">
                
                <div class="card-header">
                <a href="{{route('getTransactionsalpha')}}">
                    <h5 class="card-category text-success">Total Transections</h5>
                    <h3 class="card-title counter"><i class="tim-icons icon-chart-bar-32 text-success"></i> {{$merchant_Transection}}</h3>
                </a>
                </div>
            </div>
        </div>
    </div>
@endif
@endsection

@push('js')
    <script src="{{ asset('black') }}/js/plugins/chartjs.min.js"></script>
    <script>
        $(document).ready(function() {demo.initDashboardPageCharts();});
        
        
        
//      const counters = document.querySelectorAll('.counter');
// const speed = 2; // The lower the slower

// counters.forEach(counter => {
//     const updateCount = () => {
//         const target = +counter.getAttribute('data-target');
//         const count = +counter.innerText;

//         // Lower inc to slow and higher to slow
//         const inc = target / speed;

//         console.log(inc);
//         console.log(count);

//         // Check if target is reached
//         if (count < target) {
//             // Add inc to count and output in counter
//             counter.innerText = count + inc;
//             // Call function every ms
//             setTimeout(updateCount, 1);
//         } else {
//             counter.innerText = target;
//         }
//     };

//     updateCount();
// });
        
    </script>
@endpush

resources/views/send_email.blade.php
<!DOCTYPE html>

<html>

<head>

	<title>Email</title>

	 <meta charset="utf-8">

  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

    <style>

        html,

body {

    margin: 0 auto !important;

    padding: 0 !important;

    height: 100% !important;

    width: 100% !important;

    background: #f1f1f1;

}





* {

    -ms-text-size-adjust: 100%;

    -webkit-text-size-adjust: 100%;

}





div[style*="margin: 16px 0"] {

    margin: 0 !important;

}





table,

td {

    mso-table-lspace: 0pt !important;

    mso-table-rspace: 0pt !important;

}





table {

    border-spacing: 0 !important;

    border-collapse: collapse !important;

    table-layout: fixed !important;

    margin: 0 auto !important;

}





img {

    -ms-interpolation-mode:bicubic;

}



a {

    text-decoration: none;

}



*[x-apple-data-detectors],  

.unstyle-auto-detected-links *,

.aBn {

    border-bottom: 0 !important;

    cursor: default !important;

    /*color: inherit !important;*/

    text-decoration: none !important;

    font-size: inherit !important;

    font-family: inherit !important;

    font-weight: inherit !important;

    line-height: inherit !important;

}



/* What it does: Prevents Gmail from displaying a download button on large, non-linked images. */

.a6S {

    display: none !important;

    opacity: 0.01 !important;

}



/* What it does: Prevents Gmail from changing the text color in conversation threads. */

.im {

       color: #6f6f6f;

}



/* If the above doesn't work, add a .g-img class to any image in question. */

img.g-img + div {

    display: none !important;

}





@media only screen and (min-device-width: 320px) and (max-device-width: 374px) {

    u ~ div .email-container {

        min-width: 320px !important;

    }

}

/* iPhone 6, 6S, 7, 8, and X */

@media only screen and (min-device-width: 375px) and (max-device-width: 413px) {

    u ~ div .email-container {

        min-width: 375px !important;

    }

    .ggg{

    	    line-height: 30px !important;

    }

}

/* iPhone 6+, 7+, and 8+ */

@media only screen and (min-device-width: 414px) {

    u ~ div .email-container {

        min-width: 414px !important;

    }

}





    </style>



    <!-- CSS Reset : END -->



    <!-- Progressive Enhancements : BEGIN -->

    <style>



	    .primary{

	background: #f5564e;

}

.bg_white{

	background: #ffffff;

}

.bg_light{

	background: #fafafa;

}

.bg_black{

	background: #000000;

}

.bg_dark{

	background: #ffcd33;

}

.email-section{

	padding:2.5em 2.5em 0;

}



/*BUTTON*/

.btn{

	padding: 5px 15px;

	display: inline-block;

}

.btn.btn-primary{

	border-radius: 5px;

	background: #f5564e;

	color: #ffffff;

}

.btn.btn-white{

	border-radius: 5px;

	background: #ffffff;

	color: #000000;

}

.btn.btn-white-outline{

	border-radius: 5px;

	background: transparent;

	border: 1px solid #fff;

	color: #fff;

}



h1,h2,h3,h4,h5,h6{

	font-family: 'Nunito Sans', sans-serif;

	color: #000000;

	margin-top: 0;

}



body{

	font-family: 'Nunito Sans', sans-serif;

	font-weight: 400;

	font-size: 15px;

	line-height: 1.8;

	/*color: rgba(0,0,0,.4);*/

}



a{

	/*color: #f5564e;*/

}



table{

}

/*LOGO*/



.logo h1{

	margin: 0;

}

.logo h1 a{

	color: #000;

	font-size: 20px;

	font-weight: 700;

	text-transform: uppercase;

	font-family: 'Nunito Sans', sans-serif;

}



.navigation{

	padding: 0;

}

.navigation li{

	list-style: none;

	display: inline-block;;

	margin-left: 5px;

	font-size: 12px;

	font-weight: 700;

	text-transform: uppercase;

}

.navigation li a{

	/*color: rgba(0,0,0,.6);*/

}



/*HERO*/

.hero{

	position: relative;

	z-index: 0;

}

.hero .overlay{

	position: absolute;

	top: 0;

	left: 0;

	right: 0;

	bottom: 0;

	content: '';

	width: 100%;

	background: #00000040;

	z-index: -1;

	opacity: .3;

}

.hero .icon{

}

.hero .icon a{

	display: block;

	width: 60px;

	margin: 0 auto;

}

.hero .text{

	/*color: rgba(255,255,255,.8);*/

	padding: 0 4em;

}

.hero .text h2{

	color: #ffffff;

	font-size:32px;

	margin-bottom: 0;

	line-height: 1.2;

	font-weight: 900;

}





/*HEADING SECTION*/

.heading-section{

}

.heading-section h2{

	color: #000000;

	font-size: 24px;

	margin-top: 0;

	line-height: 1.4;

	font-weight: 700;

}

.heading-section .subheading{

	margin-bottom: 20px !important;

	display: inline-block;

	font-size: 13px;

	text-transform: uppercase;

	letter-spacing: 2px;

	/*color: rgba(0,0,0,.4);*/

	position: relative;

}

.heading-section .subheading::after{

	position: absolute;

	left: 0;

	right: 0;

	bottom: -10px;

	content: '';

	width: 100%;

	height: 2px;

	background: #f5564e;

	margin: 0 auto;

}



.heading-section-white{

	/*color: rgba(255,255,255,.8);*/

}

.heading-section-white h2{

	font-family: 

	line-height: 1;

	padding-bottom: 0;

}

.heading-section-white h2{

	/*color: #ffffff;*/

}

.heading-section-white .subheading{

	margin-bottom: 0;

	display: inline-block;

	font-size: 13px;

	text-transform: uppercase;

	letter-spacing: 2px;

	/*color: rgba(255,255,255,.4);*/

}





.icon{

	text-align: center;

}

.icon img{

}





/*SERVICES*/

.services{

	background: rgba(0,0,0,.03);

}

.text-services{

	padding: 10px 10px 0; 

	text-align: center;

}

.text-services h3{

	font-size: 16px;

	font-weight: 600;

}



.services-list{

	padding: 0;

	margin: 0 0 10px 0;

	width: 100%;

	float: left;

}



.services-list .text{

	width: 100%;

	float: right;

}

.services-list h3{

	margin-top: 0;

	margin-bottom: 0;

	font-size: 18px;

}

.services-list p{

	margin: 0;

}





/*DESTINATION*/

.text-tour{

	padding-top: 10px;

}

.text-tour h3{

	margin-bottom: 0;

}

.text-tour h3 a{

	color: #000;

}



/*BLOG*/

.text-services .meta{

	text-transform: uppercase;

	font-size: 14px;

}



/*TESTIMONY*/

.text-testimony .name{

	margin: 0;

}

.text-testimony .position{

	color: rgba(0,0,0,.3);



}





/*COUNTER*/

.counter{

	width: 100%;

	position: relative;

	z-index: 0;

}

.counter .overlay{

	position: absolute;

	top: 0;

	left: 0;

	right: 0;

	bottom: 0;

	content: '';

	width: 100%;

	background: #000000;

	z-index: -1;

	opacity: .3;

}

.counter-text{

	text-align: center;

}

.counter-text .num{

	display: block;

	color: #ffffff;

	font-size: 34px;

	font-weight: 700;

}

.counter-text .name{

	display: block;

	color: rgba(255,255,255,.9);

	font-size: 13px;

}

.price{

color: #ffcd33 !important;

}



ul.social{

	padding: 0;

}

ul.social li{

	display: inline-block;

}



/*FOOTER*/



.footer{

	color: rgba(255,255,255,.5);



}

.footer .heading{

	color: #ffffff;

	font-size: 20px;

}

.footer ul{

	margin: 0;

	padding: 0;

}

.footer ul li{

	list-style: none;

	margin-bottom: 10px;

}

.footer ul li a{

	color: rgba(255,255,255,1);

}





@media screen and (max-width: 500px) {



	.icon{

		text-align: left;

	}



	.text-services{

		padding-left: 0;

		padding-right: 20px;

		text-align: left;

	}



}





    </style>

</head>

<body>

	<div class="container">

		<div class="table_email" style="background-color: #fff; padding-top: 30px; text-align: center;">

	

	



                                    
             <img src="{{url('public/logo.png')}}" alt="Evernote" > <br>
             <h2 style="text-align: center; ">Merchantnode Login Credentials</h2>

<h2 style="text-align: center; color: #ffcd33;"> @if(isset($name))Hello  {{$name}} @endif</h2>

	<div class="link_site">

		<p style="text-align: center;">

                    
                      <div class="row" style="text-align: center; ">
					    <h3>Email:    <strong> {{$user_mail}}</strong> </h3>
					    </div>
					   <div class="row" style="text-align: center; "> 
					    <h3>Password:   <strong style="    font-size: 20px;
    font-weight: 500;">{{$user_pass}}</strong> </h3>
						</div>
						<br>
						<a href="http://merchantnode.stepinnsolution.com/login" style="padding: 10px;    background: #ffcd33;    border-radius: 6px;    color: #000;">Click here to login.</a>


		</p>







</div>



</body>

</html>